# Generated by Django 4.1.2 on 2022-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
