# Generated by Django 4.1.2 on 2022-10-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('things', '0002_user_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Thing',
        ),
    ]
